-- MySQL Script generated by MySQL Workbench
-- 02/25/16 22:26:55
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`high_priority_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`high_priority_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`high_priority_users` (
  `high_priority_usersID` INT(11) NOT NULL AUTO_INCREMENT,
  `victimID` INT(11) NOT NULL,
  PRIMARY KEY (`high_priority_usersID`),
  INDEX `victimID_idx` (`victimID` ASC),
  CONSTRAINT `victimID`
    FOREIGN KEY (`victimID`)
    REFERENCES `mydb`.`victim` (`victimID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attacker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attacker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attacker` (
  `attackerID` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attackerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`victim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`victim` ;

CREATE TABLE IF NOT EXISTS `mydb`.`victim` (
  `victimID` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_address` MEDIUMTEXT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`victimID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attack` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attack` (
  `attackID` INT(11) NOT NULL AUTO_INCREMENT,
  `source_ip` MEDIUMTEXT NOT NULL,
  `source_port` MEDIUMTEXT NOT NULL,
  `attackerID` INT(11) NOT NULL,
  `destination_ip` MEDIUMTEXT NOT NULL,
  `destination_port` MEDIUMTEXT NOT NULL,
  `victimID` INT(11) NOT NULL COMMENT '	',
  `attack_name` VARCHAR(45) NOT NULL,
  `protocol` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `attack_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`attackID`),
  INDEX `attackerID_idx` (`attackerID` ASC),
  INDEX `victimID_idx` (`victimID` ASC),
  CONSTRAINT `attackerID`
    FOREIGN KEY (`attackerID`)
    REFERENCES `mydb`.`attacker` (`attackerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `victimID`
    FOREIGN KEY (`victimID`)
    REFERENCES `mydb`.`victim` (`victimID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `mydb`.`response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`response` ;

CREATE TABLE IF NOT EXISTS `mydb`.`response` (
  `responseID` INT(11) NOT NULL AUTO_INCREMENT,
  `responsecol` TIMESTAMP NOT NULL,
  `attackID` INT(11) NOT NULL,
  PRIMARY KEY (`responseID`),
  INDEX `fk_response_1_idx` (`attackID` ASC),
  CONSTRAINT `fk_response_1`
    FOREIGN KEY (`attackID`)
    REFERENCES `mydb`.`attack` (`attackID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TCP_Reset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TCP_Reset` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TCP_Reset` (
  `tcp_resetID` INT(11) NOT NULL AUTO_INCREMENT,
  `responseID` INT(11) NOT NULL,
  PRIMARY KEY (`tcp_resetID`),
  INDEX `responseID_idx` (`responseID` ASC),
  CONSTRAINT `responseID`
    FOREIGN KEY (`responseID`)
    REFERENCES `mydb`.`response` (`responseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Timebased_Block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Timebased_Block` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Timebased_Block` (
  `timebased_blockID` INT(11) NOT NULL AUTO_INCREMENT,
  `responseID` INT(11) NOT NULL,
  `time_blocked` TIMESTAMP NOT NULL,
  PRIMARY KEY (`timebased_blockID`),
  INDEX `responseID_idx` (`responseID` ASC),
  CONSTRAINT `responseID`
    FOREIGN KEY (`responseID`)
    REFERENCES `mydb`.`response` (`responseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permanent_Block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permanent_Block` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permanent_Block` (
  `permanent_blockID` INT(11) NOT NULL AUTO_INCREMENT,
  `responseID` INT(11) NOT NULL,
  PRIMARY KEY (`permanent_blockID`),
  INDEX `responseID_idx` (`responseID` ASC),
  CONSTRAINT `responseID`
    FOREIGN KEY (`responseID`)
    REFERENCES `mydb`.`response` (`responseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`high_priority_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`high_priority_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`high_priority_users` (
  `high_priority_usersID` INT(11) NOT NULL AUTO_INCREMENT,
  `victimID` INT(11) NOT NULL,
  PRIMARY KEY (`high_priority_usersID`),
  INDEX `victimID_idx` (`victimID` ASC),
  CONSTRAINT `victimID`
    FOREIGN KEY (`victimID`)
    REFERENCES `mydb`.`victim` (`victimID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attack_persistence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attack_persistence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attack_persistence` (
  `attack_persistenceID` INT(11) NOT NULL AUTO_INCREMENT,
  `attackID` INT(11) NOT NULL,
  `to_monitor` TINYINT(1) NOT NULL,
  `response` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attack_persistenceID`),
  INDEX `attackID_idx` (`attackID` ASC),
  CONSTRAINT `attackID`
    FOREIGN KEY (`attackID`)
    REFERENCES `mydb`.`attack` (`attackID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`time_interval_persistence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`time_interval_persistence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`time_interval_persistence` (
  `time_interval_persistenceID` INT(11) NOT NULL AUTO_INCREMENT,
  `attack_persistenceID` INT(11) NOT NULL,
  `time_persistence` TIMESTAMP NOT NULL,
  `time_interval_date` DATE NOT NULL,
  PRIMARY KEY (`time_interval_persistenceID`),
  INDEX `attack_persistenceID_idx` (`attack_persistenceID` ASC),
  CONSTRAINT `attack_persistenceID`
    FOREIGN KEY (`attack_persistenceID`)
    REFERENCES `mydb`.`attack_persistence` (`attack_persistenceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
